### ISSUE TITLE
Highlight React components

### ISSUE THREAD

**Issue by benjaminbenais** [Sukadia/sukadia.dev-dark#1]
Hi, thanks for improving the original theme :)

It would be nice to have React components highlighted as well (it is white at the moment). Thanks !

<img width="310" alt="Screenshot 2022-04-11 at 11 48 08" src="https://user-images.githubusercontent.com/45941603/162713559-c2bb6b6c-6836-4c27-88b0-0622f3cf71e8.png">
<img width="497" alt="Screenshot 2022-04-11 at 11 50 56" src="https://user-images.githubusercontent.com/45941603/162713563-5b488ab9-d01e-4862-9b60-c69f96ce437e.png">

**Comment by Sukadia** [comment]
This has been added in 1.0.4 :)
